default: &default
  adapter: mysql2
  encoding: utf8
  database: <%= ENV['MARIADB_DATABASE'] %>_XXX
  username: <%= ENV['MARIADB_USERNAME'] %>
  password: <%= ENV['MARIADB_PASSWORD'] %>
  pool: 10
  port: 3306
  reconnect: true

development:
  <<: *default
  database: <%= ENV['MARIADB_DATABASE'] %>_development

test:
  <<: *default
  database: <%= ENV['MARIADB_DATABASE'] %>_test

production:
  adapter: mysql2
  encoding: utf8
  database: <%= ENV['MYSQL_DATABASE'] %>
  username: <%= ENV['MYSQL_USERNAME'] %>
  password: <%= ENV['MYSQL_PASSWORD'] %>
  pool: 10
  port: 3306
  socket: /var/lib/mysql/mysql.sock
  reconnect: true