# This workflow uses actions that are not certified by GitHub.  They are
# provided by a third-party and are governed by separate terms of service,
# privacy policy, and support documentation.
#
# This workflow will install a prebuilt Ruby version, install dependencies, and
# run tests and linters.
name: "Ruby on Rails CI"
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
jobs:
  test:
    runs-on: ubuntu-latest
    services:
      mariadb:
        image: mariadb:10
        env:
          MARIADB_RANDOM_ROOT_PASSWORD: true
          MARIADB_DATABASE: sqek_test
          MARIADB_USER: rails
          MARIADB_PASSWORD: password
        ports:
          - 3306:3306
        options: >-
          --health-cmd "mysql sqek_test -urails -ppassword -e 'SELECT 1;' || exit 1"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    env:
      RAILS_ENV: test
      DATABASE_URL: "mysql2://rails:password@127.0.0.1:3306/sqek_test"
    steps:
      - name: Pull repository
        uses: actions/checkout@v4

      - name: Set up Node and yarn cache
        uses: actions/setup-node@v4.0.2
        with:
          node-version: 16
          cache: yarn

      - name: yarn install
        run: yarn install --frozen-lockfile

      - name: Bundle install and cache result
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: assets precompile
        run: bundle exec rake assets:precompile --trace

      # Add or replace database setup steps here
      - name: Set up database schema
        run: bin/rails db:schema:load
      # Add or replace test runners here
      - name: Run tests
        run: bin/rake
